home:
  methods: GET
  path: /
  controller: App\Controller\HomeController::index

help_request:
  methods: GET|POST
  path: /ziadost-o-pomoc
  controller: App\Controller\HelpRequestController::index

help_request_success:
  methods: GET
  path: /ziadost-o-pomoc/dakujeme
  controller: App\Controller\HelpRequestController::success

recipients:
  methods: GET
  path: /komu-sme-pomohli
  controller: App\Controller\RecipientsController::index

team:
  methods: GET
  path: /organizacny-team
  controller: App\Controller\TeamController::index

faq:
  methods: GET
  path: /faq
  controller: App\Controller\FaqController::index

partners:
  methods: GET
  path: /garanti
  controller: App\Controller\PartnersController::index

donation:
  methods: GET|POST
  path: /darujem
  controller: App\Controller\DonationController::index

donation_success:
  methods: GET|POST
  path: /darujem/dakujeme
  controller: App\Controller\DonationController::success

policy:
  methods: GET
  path: /pravidla-ochrany-osobnych-udajov
  controller: App\Controller\PolicyController::index

export_dopyt:
  methods: GET
  path: /export/dopyt
  controller: App\Controller\ExportController::dopyt

export_ponuka:
  methods: GET
  path: /export/ponuka
  controller: App\Controller\ExportController::ponuka
